#!/bin/sh

echo
echo "This is a placeholder."
echo "It will be replaced in the future with a script that does the real"
echo "work of testing the helpers."
echo
echo "Here's a silly test to check whether 'ls', had it been an extfs helper,"
echo "works properly:"
echo

LC_ALL=C ls -l | ./mc_parse_ls_l

# (LC_ALL=C is meant to prevent date formats MC can't parse. This might
# still not be foolproof, but that's just a demonstration.)
