#! /bin/sh

# This script makes pretty looking patches provided that the old files
# are kept around with the .v0 suffix.

: ${backup_suffix=${1:-"\.v0"}}
backup_files=`find . -path "*$backup_suffix" -type f | sort -u`
for oldfile in $backup_files; do
  newfile=`echo $oldfile | sed 's,^\./,,;s/'$backup_suffix'$//'`
  oldlabel="$oldprefix$newfile"
  newlabel="$newprefix$newfile"
  find "$oldfile" ! -size 0 | grep . >/dev/null || \
    { oldfile="/dev/null"; oldlabel="/dev/null"; }
  find "$newfile" ! -size 0 | grep . >/dev/null || \
    { newfile="/dev/null"; newlabel="/dev/null"; }
  case $newfile in
    *.c) dflags="-u -p" ;;
    *.po) dflags='-U 1 -I^#[:,.~]';;
    *) dflags="-u" ;;
  esac
  diff $dflags -L "$oldlabel" -L "$newlabel" "$oldfile" "$newfile"
done
