#! /bin/sh
#
# Written by Erik Troan (ewt@redhat.com) 1996
#            Jakub Jelinek (jj@sunsite.mff.cuni.cz) 1996
#            Tomasz K³oczko (kloczek@rudy.mif.pg.gda.pl) 1997
# minor changes by Wojtek Pilorz (wpilorz@bdk.lublin.pl) 1997
# minor changes by Michele Marziani (marziani@fe.infn.it) 1997
# bug files by Marc Merlin (marcsoft@merlins.org) 1998
# (C) 1996 The Free Software Foundation.
#
#

mcrpmfs_list ()
{
    # set MCFASTRPM_DFLT to 1 for faster rpm files handling by default, to 0 for
    # slower handling
    MCFASTRPM_DFLT=0
    if test -z "$MCFASTRPM"; then
      MCFASTRPM=$MCFASTRPM_DFLT
    fi
    FILEPREF="-r--r--r--   1 root     root    "
    DESC=`rpm -qip "$1"`
    DATE=`rpm -qp --qf "%{BUILDTIME:date}\n" "$1" | cut -c 5-11,21-24`
    HEADERSIZE=`echo "$DESC" | wc -c`
    echo "-r--r--r--   1 root     root  $HEADERSIZE $DATE HEADER"
    echo "-r-xr-xr-x   1 root     root    39 $DATE INSTALL"
    echo "-r-xr-xr-x   1 root     root    39 $DATE UPGRADE"
    echo "dr-xr-xr-x   3 root     root	   0 $DATE INFO"
    echo "$FILEPREF 0 $DATE INFO/NAME-VERSION-RELEASE"
    echo "$FILEPREF 0 $DATE INFO/GROUP"
    echo "$FILEPREF 0 $DATE INFO/BUILDHOST"
    echo "$FILEPREF 0 $DATE INFO/SOURCERPM"
    if test "$MCFASTRPM" = 0 ; then
     test "`rpm -qp --qf \"%{DISTRIBUTION}\" \"$1\"`" = "(none)" ||
 	 echo "$FILEPREF 0 $DATE INFO/DISTRIBUTION"
     test "`rpm -qp --qf \"%{VENDOR}\" \"$1\"`" = "(none)" ||
	 echo "$FILEPREF 0 $DATE INFO/VENDOR"
     test "`rpm -qp --qf \"%{DESCRIPTION}\" \"$1\"`" = "(none)" ||
         echo "$FILEPREF 0 $DATE INFO/DESCRIPTION"
     test "`rpm -qp --qf \"%{SUMMARY}\" \"$1\"`" = "(none)" ||
         echo "$FILEPREF 0 $DATE INFO/SUMMARY"
     if test "`rpm -qp --qf \"%{RPMTAG_PREIN}%{RPMTAG_POSTIN}%{RPMTAG_PREUN}%{RPMTAG_POSTUN}%{VERIFYSCRIPT}\" \"$1\"`" != "(none)(none)(none)(none)(none)"; then
	echo "dr-xr-xr-x   1 root     root     0 $DATE INFO/SCRIPTS"
	test "`rpm -qp --qf \"%{RPMTAG_PREIN}\" \"$1\"`" = '(none)' ||
	   echo "$FILEPREF 0 $DATE INFO/SCRIPTS/PREIN"
	test "`rpm -qp --qf \"%{RPMTAG_POSTIN}\" \"$1\"`" = '(none)' ||
	   echo "$FILEPREF 0 $DATE INFO/SCRIPTS/POSTIN"
	test "`rpm -qp --qf \"%{RPMTAG_PREUN}\" \"$1\"`" = '(none)' ||
	   echo "$FILEPREF 0 $DATE INFO/SCRIPTS/PREUN"
	test "`rpm -qp --qf \"%{RPMTAG_POSTUN}\" \"$1\"`" = '(none)' ||
	   echo "$FILEPREF 0 $DATE INFO/SCRIPTS/POSTUN"
	test "`rpm -qp --qf \"%{VERIFYSCRIPT}\" \"$1\"`" = '(none)' ||
	   echo "$FILEPREF 0 $DATE INFO/SCRIPTS/VERIFYSCRIPT"
        echo "$FILEPREF 0 $DATE INFO/SCRIPTS/ALL"
     fi
    else
     echo "$FILEPREF 0 $DATE INFO/DISTRIBUTION"
     echo "$FILEPREF 0 $DATE INFO/VENDOR"
     echo "$FILEPREF 0 $DATE INFO/DESCRIPTION"
     echo "$FILEPREF 0 $DATE INFO/SUMMARY"
     echo "dr-xr-xr-x   1 root     root     0 $DATE INFO/SCRIPTS"
     echo "$FILEPREF 0 $DATE INFO/SCRIPTS/PREIN"
     echo "$FILEPREF 0 $DATE INFO/SCRIPTS/POSTIN"
     echo "$FILEPREF 0 $DATE INFO/SCRIPTS/PREUN"
     echo "$FILEPREF 0 $DATE INFO/SCRIPTS/POSTUN"
     echo "$FILEPREF 0 $DATE INFO/SCRIPTS/VERIFYSCRIPT"
     echo "$FILEPREF 0 $DATE INFO/SCRIPTS/ALL"
    fi
    if test "$MCFASTRPM" = 0 ; then
     test "`rpm -qp --qf \"%{PACKAGER}\" \"$1\"`" = "(none)" ||
	 echo "$FILEPREF 0 $DATE INFO/PACKAGER"
     test "`rpm -qp --qf \"%{URL}\" \"$1\"`" = "(none)" ||
	 echo "$FILEPREF 0 $DATE INFO/URL"
     test "`rpm -qp --qf \"%{SERIAL}\" \"$1\"`" = "(none)" ||
	 echo "$FILEPREF 0 $DATE INFO/SERIAL"
     test "`rpm -qp --qf \"%{COPYRIGHT}\" \"$1\"`" = "(none)" ||
	 echo "$FILEPREF 0 $DATE INFO/COPYRIGHT"
     test "`rpm -qp --qf \"%{LICENSE}\" \"$1\"`" = "(none)" ||
	 echo "$FILEPREF 0 $DATE INFO/LICENSE"
    else
	 echo "$FILEPREF 0 $DATE INFO/PACKAGER"
	 echo "$FILEPREF 0 $DATE INFO/URL"
	 echo "$FILEPREF 0 $DATE INFO/SERIAL"
	 echo "$FILEPREF 0 $DATE INFO/COPYRIGHT"
	 echo "$FILEPREF 0 $DATE INFO/LICENSE"
    fi
    echo "$FILEPREF 0 $DATE INFO/BUILDTIME"
    echo "$FILEPREF 0 $DATE INFO/RPMVERSION"
    echo "$FILEPREF 0 $DATE INFO/OS"
    echo "$FILEPREF 0 $DATE INFO/SIZE"
    if test "$MCFASTRPM" != 0 ; then
    rpm -qp --qf "[%{REQUIRENAME}\n]" "$1" | grep "(none)" > /dev/null ||
	echo "$FILEPREF 0 $DATE INFO/REQUIRENAME"
    rpm -qp --qf "[%{OBSOLETES}\n]" "$1" | grep "(none)" > /dev/null ||
	echo "$FILEPREF 0 $DATE INFO/OBSOLETES"
    rpm -qp --qf "[%{PROVIDES}\n]" "$1" | grep "(none)" > /dev/null ||
	echo "$FILEPREF 0 $DATE INFO/PROVIDES"
    test "`rpm -qp --qf \"%{CHANGELOGTEXT}\" \"$1\"`" = "(none)" ||
       echo "$FILEPREF 0 $DATE INFO/CHANGELOG"
    else 
	echo "$FILEPREF 0 $DATE INFO/REQUIRENAME"
	echo "$FILEPREF 0 $DATE INFO/OBSOLETES"
	echo "$FILEPREF 0 $DATE INFO/PROVIDES"
        echo "$FILEPREF 0 $DATE INFO/CHANGELOG"
    fi

    rpm -qlvp "$1" | sed -e 's/^\(..........\)[-t]* /\1 1 /'
}

mcrpmfs_copyout ()
{
    case "$2" in
	HEADER) rpm -qip "$1" > "$3"; exit 0;;
	INSTALL) echo "# Run this to install this RPM package" > "$3"; exit 0;;
	UPGRADE) echo "# Run this to upgrade this RPM package" > "$3"; exit 0;;
	INFO/NAME-VERSION-RELEASE)	rpm -qp --qf "%{NAME}-%{VERSION}-%{RELEASE}\n" "$1" > "$3"; exit 0;;
	INFO/RELEASE)		rpm -qp --qf "%{RELEASE}\n" "$1" > "$3"; exit 0;;
	INFO/GROUP)		rpm -qp --qf "%{GROUP}\n" "$1" > "$3"; exit 0;;
	INFO/DISTRIBUTION) 	rpm -qp --qf "%{DISTRIBUTION}\n" "$1" > "$3"; exit 0;;
	INFO/VENDOR)		rpm -qp --qf "%{VENDOR}\n" "$1" > "$3"; exit 0;;
	INFO/BUILDHOST)		rpm -qp --qf "%{BUILDHOST}\n" "$1" > "$3"; exit 0;;
	INFO/SOURCERPM)		rpm -qp --qf "%{SOURCERPM}\n" "$1" > "$3"; exit 0;;
	INFO/DESCRIPTION)	rpm -qp --qf "%{DESCRIPTION}\n" "$1" > "$3"; exit 0;;
	INFO/PACKAGER)		rpm -qp --qf "%{PACKAGER}\n" "$1" > "$3"; exit 0;;
	INFO/URL)		rpm -qp --qf "%{URL}\n" "$1" >"$3"; exit 0;;
	INFO/BUILDTIME)		rpm -qp --qf "%{BUILDTIME:date}\n" "$1" >"$3"; exit 0;;
	INFO/SERIAL)		rpm -qp --qf "%{SERIAL}\n" "$1" >"$3"; exit 0;;
	INFO/COPYRIGHT)		rpm -qp --qf "%{COPYRIGHT}\n" "$1" >"$3"; exit 0;;
	INFO/RPMVERSION)	rpm -qp --qf "%{RPMVERSION}\n" "$1" >"$3"; exit 0;;
	INFO/REQUIRENAME)	rpm -qp --qf "[%{REQUIRENAME} %{REQUIREFLAGS:depflags} %{REQUIREVERSION}\n]" "$1" >"$3"; exit 0;;
	INFO/PROVIDES)		rpm -qp --qf "[%{PROVIDES}\n]" "$1" >"$3"; exit 0;;
	INFO/SCRIPTS/PREIN)	rpm -qp --qf "%{RPMTAG_PREIN}\n" "$1" >"$3"; exit 0;;
	INFO/SCRIPTS/POSTIN)	rpm -qp --qf "%{RPMTAG_POSTIN}\n" "$1" >"$3"; exit 0;;
	INFO/SCRIPTS/PREUN)	rpm -qp --qf "%{RPMTAG_PREUN}\n" "$1" >"$3"; exit 0;;
	INFO/SCRIPTS/POSTUN)	rpm -qp --qf "%{RPMTAG_POSTUN}\n" "$1" >"$3"; exit 0;;
	INFO/SCRIPTS/VERIFYSCRIPT)	rpm -qp --qf "%{VERIFYSCRIPT}\n" "$1" >"$3"; exit 0;;
	INFO/SCRIPTS/ALL)		rpm -qp --scripts "$1" > "$3"; exit 0;;
	INFO/SUMMARY)		rpm -qp --qf "%{SUMMARY}\n" "$1" > "$3"; exit 0;;
	INFO/OS)		rpm -qp --qf "%{OS}\n" "$1" > "$3"; exit 0;;
	INFO/CHANGELOG)		rpm -qp --qf "[* %{CHANGELOGTIME:date} %{CHANGELOGNAME}\n%{CHANGELOGTEXT}\n\n]\n" "$1" > "$3"; exit 0;;
	INFO/SIZE)		rpm -qp --qf "%{SIZE} bytes\n" "$1" > "$3"; exit 0;;
	*)
	    TMPDIR=/tmp/mctmpdir.$$
	    mkdir $TMPDIR || exit 1
	    cd $TMPDIR
	    rpm2cpio "$1" | cpio -iumd --quiet "$2" >/dev/null
	    mv "$2" "$3"
	    cd /
	    rm -rf $TMPDIR;;
    esac
}

mcrpmfs_run ()
{
    case "$2" in
	INSTALL) echo "Installing \"$1\""; rpm -ivh "$1"; exit 0;;
	UPGRADE) echo "Upgrading \"$1\""; rpm -iUvh "$1"; exit 0;;
    esac
}

# override any locale for dates
LC_ALL=C
export LC_ALL

umask 077
case "$1" in
  list) mcrpmfs_list "$2"; exit 0;;
  copyout) mcrpmfs_copyout "$2" "$3" "$4"; exit 0;;
  run) mcrpmfs_run "$2" "$3"; exit 1;;
esac
exit 1
