#include <factory.idl>

module GNOME {
	interface FileManagerFactory : Factory {

	};

	exception POSIX_ERROR {};

	interface FileManager {
		void chdir (in string dir)
			raises (POSIX_ERROR);
	};
};
