#!/bin/bash
# Downloads tree-sitter grammar source files for MC editor syntax highlighting.
# Run this script from the ts-grammars/ directory to (re)download grammar sources.
#
# Usage:
#   ./download-grammars.sh               # download all grammars
#   ./download-grammars.sh c python bash # download only selected grammars
#
# Grammar files are downloaded unmodified. All compatibility is handled by the
# compat headers in tree_sitter/ and build flags in Makefile.am.
#
# Each grammar needs at minimum:
#   - parser.c (required, generated by tree-sitter)
#   - scanner.c or scanner.cc (optional, for grammars with external scanners)
# Some grammars need additional headers — these are listed per-grammar below.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# If arguments are provided, only download those grammars.
# Otherwise, download all.
REQUESTED_GRAMMARS="${*}"

should_download() {
    local lang="$1"
    if [ -z "$REQUESTED_GRAMMARS" ]; then
        return 0  # No filter, download all
    fi
    for g in $REQUESTED_GRAMMARS; do
        if [ "$g" = "$lang" ]; then
            return 0
        fi
    done
    return 1
}

download() {
    local lang="$1"
    should_download "$lang" || return 0

    local org="$2"
    local repo="$3"
    local branch="${4:-master}"
    local src_prefix="${5:-src}"

    echo "Downloading $lang from $org/$repo ($branch)..."

    mkdir -p "$lang"

    local base_url="https://raw.githubusercontent.com/$org/$repo/$branch/$src_prefix"

    curl -sfL "$base_url/parser.c" -o "$lang/parser.c" || {
        echo "  ERROR: Failed to download parser.c for $lang"
        rm -rf "$lang"
        return 1
    }

    # Try scanner.c (C scanner)
    if curl -sfL "$base_url/scanner.c" -o "$lang/scanner.c" 2>/dev/null; then
        echo '  Downloaded scanner.c'
    else
        rm -f "$lang/scanner.c"
    fi

    # Try scanner.cc (C++ scanner)
    if curl -sfL "$base_url/scanner.cc" -o "$lang/scanner.cc" 2>/dev/null; then
        echo '  Downloaded scanner.cc'
    else
        rm -f "$lang/scanner.cc"
    fi

    echo "  OK"
}

# Download grammar from GitLab (different URL format)
download_gitlab() {
    local lang="$1"
    should_download "$lang" || return 0

    local org="$2"
    local repo="$3"
    local branch="${4:-master}"
    local src_prefix="${5:-src}"

    echo "Downloading $lang from gitlab.com/$org/$repo ($branch)..."

    mkdir -p "$lang"

    local base_url="https://gitlab.com/$org/$repo/-/raw/$branch/$src_prefix"

    curl -sfL "$base_url/parser.c" -o "$lang/parser.c" || {
        echo "  ERROR: Failed to download parser.c for $lang"
        rm -rf "$lang"
        return 1
    }

    # Try scanner.c (C scanner)
    if curl -sfL "$base_url/scanner.c" -o "$lang/scanner.c" 2>/dev/null; then
        echo '  Downloaded scanner.c'
    else
        rm -f "$lang/scanner.c"
    fi

    echo '  OK'
}

# Helper to download an extra file into a grammar directory
download_extra() {
    local lang="$1"
    should_download "$lang" || return 0

    local org="$2"
    local repo="$3"
    local branch="$4"
    local remote_path="$5"
    local local_name="${6:-$(basename "$remote_path")}"

    local url="https://raw.githubusercontent.com/$org/$repo/$branch/$remote_path"

    curl -sfL "$url" -o "$lang/$local_name" || {
        echo "  WARNING: Failed to download extra file $remote_path for $lang"
        return 0
    }
    echo "  Downloaded $local_name"
}

# ============================================================================
# Official grammars (tree-sitter org)
# Pinned to specific Git tags or commit SHAs.
# ============================================================================

download bash       tree-sitter tree-sitter-bash        v0.25.1
download c          tree-sitter tree-sitter-c           v0.24.1
download cpp        tree-sitter tree-sitter-cpp         v0.23.4
download c_sharp    tree-sitter tree-sitter-c-sharp     v0.23.1
download css        tree-sitter tree-sitter-css         v0.25.0
download go         tree-sitter tree-sitter-go          v0.25.0

download haskell    tree-sitter tree-sitter-haskell     v0.23.1
download_extra haskell tree-sitter tree-sitter-haskell  v0.23.1 src/unicode.h

download html       tree-sitter tree-sitter-html        v0.23.2
download_extra html tree-sitter tree-sitter-html        v0.23.2 src/tag.h

download java       tree-sitter tree-sitter-java        v0.23.5
download javascript tree-sitter tree-sitter-javascript  v0.25.0
download json       tree-sitter tree-sitter-json        v0.24.8

download ocaml      tree-sitter tree-sitter-ocaml       v0.24.2 grammars/ocaml/src
download_extra ocaml tree-sitter tree-sitter-ocaml      v0.24.2 common/scanner.h common_scanner.h
should_download ocaml && sed -i 's|#include "../../../common/scanner.h"|#include "common_scanner.h"|' ocaml/scanner.c

download php        tree-sitter tree-sitter-php         v0.24.2 php/src
download_extra php tree-sitter tree-sitter-php          v0.24.2 common/scanner.h common_scanner.h
should_download php && sed -i 's|#include "../../common/scanner.h"|#include "common_scanner.h"|' php/scanner.c

download python     tree-sitter tree-sitter-python      v0.25.0
download ruby       tree-sitter tree-sitter-ruby        v0.23.1
download rust       tree-sitter tree-sitter-rust        v0.24.0
download scala      tree-sitter tree-sitter-scala       v0.25.0

# swift has no tags — pinned to commit 2024-12-19
download swift      tree-sitter tree-sitter-swift       db675450dcc1478ee128c96ecc61c13272431aab

download typescript tree-sitter tree-sitter-typescript  v0.23.2 typescript/src
download_extra typescript tree-sitter tree-sitter-typescript v0.23.2 common/scanner.h common_scanner.h
should_download typescript && sed -i 's|#include "../../common/scanner.h"|#include "common_scanner.h"|' typescript/scanner.c

download verilog    tree-sitter tree-sitter-verilog     v1.0.3

# ============================================================================
# Community grammars (tree-sitter-grammars org)
# Pinned to specific Git tags or commit SHAs.
# ============================================================================

download cuda       tree-sitter-grammars tree-sitter-cuda       v0.21.1
download diff       tree-sitter-grammars tree-sitter-diff       v0.1.0
download glsl       tree-sitter-grammars tree-sitter-glsl       v0.2.0
download hcl        tree-sitter-grammars tree-sitter-hcl        v1.2.0
download kotlin     tree-sitter-grammars tree-sitter-kotlin     v1.1.0
download lua        tree-sitter-grammars tree-sitter-lua        v0.5.0
download make       tree-sitter-grammars tree-sitter-make       v1.1.1

download markdown        tree-sitter-grammars tree-sitter-markdown   v0.5.3 tree-sitter-markdown/src
download markdown_inline tree-sitter-grammars tree-sitter-markdown   v0.5.3 tree-sitter-markdown-inline/src

download meson      tree-sitter-grammars tree-sitter-meson      v1.3.0

# po has no tags — pinned to commit 2024-12-10
download po         tree-sitter-grammars tree-sitter-po         bd860a0f57f697162bf28e576674be9c1500db5e

download properties tree-sitter-grammars tree-sitter-properties v0.3.0

# tcl has no tags — pinned to commit 2025-03-02
download tcl        tree-sitter-grammars tree-sitter-tcl        8f11ac7206a54ed11210491cee1e0657e2962c47

download toml       tree-sitter-grammars tree-sitter-toml       v0.7.0

download xml        tree-sitter-grammars tree-sitter-xml        v0.7.0 xml/src
download_extra xml tree-sitter-grammars tree-sitter-xml         v0.7.0 common/scanner.h common_scanner.h
should_download xml && sed -i 's|#include "../../common/scanner.h"|#include "common_scanner.h"|' xml/scanner.c

download yaml       tree-sitter-grammars tree-sitter-yaml       v0.7.2
download_extra yaml tree-sitter-grammars tree-sitter-yaml       v0.7.2 src/schema.core.c

# ============================================================================
# Third-party grammars
# Pinned to specific Git tags or commit SHAs.
# ============================================================================

# ada has no real tags — pinned to commit 2025-02-20
download ada        briot                tree-sitter-ada         6b58259a08b1a22ba0247a7ce30be384db618da6

download awk        Beaglefoot           tree-sitter-awk         v0.7.2
download cmake      uyha                 tree-sitter-cmake       v0.7.2
download d          gdamore              tree-sitter-d           v0.8.2
download dockerfile camdencheek          tree-sitter-dockerfile  v0.2.0

# erlang has no tags — pinned to commit 2025-02-18
download erlang     AbstractMachinesLab  tree-sitter-erlang      3a9c769444f08bbccce03845270efac0c641c5e7

download fortran    stadelmanma          tree-sitter-fortran     v0.5.1
download ini        justinmk             tree-sitter-ini         v1.4.0
download lisp       theHamsta            tree-sitter-commonlisp  v0.4.1
download pascal     Isopod               tree-sitter-pascal      v0.10.2

# perl has no tags — pinned to commit on release branch 2025-02-23
download perl       tree-sitter-perl     tree-sitter-perl        0c24d001dd1921e418fb933d208a7bd7dd3f923a
download_extra perl tree-sitter-perl tree-sitter-perl            0c24d001dd1921e418fb933d208a7bd7dd3f923a src/tsp_unicode.h

download r          r-lib                tree-sitter-r           v1.2.0

# sql has no tags — pinned to commit 2024-10-01
download sql        m-novikov            tree-sitter-sql         587f30d184b058450be2a2330878210c5f33b3f9

# vhdl has no tags — pinned to commit 2023-11-13
download vhdl       alemuller            tree-sitter-vhdl        a3b2d84990527c7f8f4ae219c332c00c33d2d8e5

# asm (x86 assembly, for MC's assembler.syntax) — pinned to commit 2025-03-02
download asm        RubixDev            tree-sitter-asm          839741fef4dab5128952334624905c82b40c7133

# bison (Yacc/Bison, for MC's yxx.syntax) — hosted on GitLab, pinned to commit 2024-01-07
download_gitlab bison btuin2            tree-sitter-bison        0681f9d1d21bbccdc44ab5241426409b4313f9b5

# caddy (Caddyfile) — pinned to commit 2025-01-25
download caddy      opa-oz              tree-sitter-caddy        9b3fde99d3d74345b85b655a6d8065e004fbe26f

# cobol — WARNING: 30MB parser.c, function is tree_sitter_COBOL (uppercase), pinned to commit 2025-02-28
download cobol      yutaro-sakamoto     tree-sitter-cobol        e99dbdc3d800d5fa2796476efd60af91f6b43d93

# dot (Graphviz DOT) — pinned to commit 2024-04-16
download dot        rydesun             tree-sitter-dot          80327abbba6f47530edeb0df9f11bd5d5c93c14d

# idl (Interface Definition Language) — pinned to commit 2025-01-09
download idl        cathaysia           tree-sitter-idl          e07d32972b41cc4c02cfd49f9df2abaa3ae54303

# matlab (for MC's octave.syntax) — pinned to commit 2025-02-28
download matlab     acristoffers        tree-sitter-matlab       c2390a59016f74e7d5f75ef09510768b4f30217e

# muttrc (Mutt/NeoMutt config) — pinned to commit 2025-03-05
download muttrc     neomutt             tree-sitter-muttrc       173b0ab53a9c07962c9777189c4c70e90f1c1837

# proto (Protocol Buffers) — pinned to commit 2025-01-18
download proto      coder3101           tree-sitter-proto        eacb7f162e35a18a0dd8ce734f7e7baf2a8398ca

# smalltalk — pinned to commit 2024-04-30
download smalltalk  tom95               tree-sitter-smalltalk    f5d63d37ebb135fd0eb0441a51d5ccdf933c6537

# strace — pinned to commit 2025-01-14
download strace     sigmaSd             tree-sitter-strace       ac874ddfcc08d689fee1f4533789e06d88388f29

# turtle (RDF Turtle) — pinned to commit 2024-10-09
download turtle     GordianDziwis       tree-sitter-turtle       7f789ea7ef765080f71a298fc96b7c957fa24422

# ============================================================================
# Post-download: create stub files needed for compilation
# ============================================================================

# The perl grammar's tsp_unicode.h includes "bsearch.h" which conflicts
# with libc's bsearch function. Provide a stub that just includes stdlib.h.
if should_download perl; then
    echo 'Creating perl/bsearch.h stub...'
    cat > perl/bsearch.h << 'STUB'
/* Stub: perl grammar's tsp_unicode.h includes "bsearch.h" but we only
   need the standard library bsearch() which is in stdlib.h. */
#include <stdlib.h>
STUB
fi

echo ''
echo 'Done. Downloaded grammars for $(ls -d */ 2>/dev/null | wc -l) languages.'
echo ''
echo 'Grammar files are unmodified. All compatibility is handled by:'
echo '  tree_sitter/parser.h  -- compat header (REDUCE macro, TSFieldMapSlice, etc.)'
echo '  Makefile.am           -- include paths, warning suppression'
echo '  perl/bsearch.h        -- stub for libc conflict'
